# Generated by Django 5.0 on 2023-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=255)),
                ('tonality', models.CharField(max_length=2)),
                ('note_1', models.CharField(max_length=2)),
                ('note_2', models.CharField(max_length=2)),
                ('note_3', models.CharField(max_length=2)),
                ('note_4', models.CharField(max_length=2)),
                ('note_5', models.CharField(max_length=2)),
                ('note_6', models.CharField(max_length=2)),
                ('note_7', models.CharField(max_length=2)),
            ],
        ),
    ]
