# Generated by Django 5.0 on 2023-12-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='note_1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_5',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_6',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='mode',
            name='note_7',
            field=models.CharField(max_length=3),
        ),
    ]
